// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC__q5B6HK_0NjDgfuXP5zfL5F4XgDqwi0',
    appId: '1:614199464699:web:28d837e311033fdd07165e',
    messagingSenderId: '614199464699',
    projectId: 'ball-by-ball-125fc',
    authDomain: 'ball-by-ball-125fc.firebaseapp.com',
    storageBucket: 'ball-by-ball-125fc.appspot.com',
    measurementId: 'G-8VD8XGFMPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsThYmEiMBPBiefvpUOrp6io5uAGIDCYA',
    appId: '1:614199464699:android:34eae0211e3fc5d107165e',
    messagingSenderId: '614199464699',
    projectId: 'ball-by-ball-125fc',
    storageBucket: 'ball-by-ball-125fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRfnQgVc6BUr1H5YDPUnj06gpU0ywb0Mk',
    appId: '1:614199464699:ios:1672b54e8a53790e07165e',
    messagingSenderId: '614199464699',
    projectId: 'ball-by-ball-125fc',
    storageBucket: 'ball-by-ball-125fc.appspot.com',
    iosBundleId: 'com.awantech.ballByBall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRfnQgVc6BUr1H5YDPUnj06gpU0ywb0Mk',
    appId: '1:614199464699:ios:1672b54e8a53790e07165e',
    messagingSenderId: '614199464699',
    projectId: 'ball-by-ball-125fc',
    storageBucket: 'ball-by-ball-125fc.appspot.com',
    iosBundleId: 'com.awantech.ballByBall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC__q5B6HK_0NjDgfuXP5zfL5F4XgDqwi0',
    appId: '1:614199464699:web:8e185b41f42e7db407165e',
    messagingSenderId: '614199464699',
    projectId: 'ball-by-ball-125fc',
    authDomain: 'ball-by-ball-125fc.firebaseapp.com',
    storageBucket: 'ball-by-ball-125fc.appspot.com',
    measurementId: 'G-GC8B7CHM6X',
  );
}
